version: '3.8'
services:
  llmevaluation-web:
    build: .
    ports:
      - "4444:5000" 
    environment:
      - FLASK_ENV=development
      - DATABASE_PATH=/app/backend/data/webui.db
    volumes:
      - shared-data:/app/backend/data
    restart: always
    command: bash -c "flask run --host=0.0.0.0"

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080" 
    volumes:
      - shared-data:/app/backend/data 
    restart: always

volumes:
  shared-data:
