openapi: 3.0.3
info:
  title: LLMevaluation Configuration & Index Endpoint
  version: "1.0.0"
  description: >
    Configuración y endpoint de inicio.  
    Agregamos valores por defecto a los parámetros de la petición.

servers:
  - url: "http://localhost:4444"
    description: "Servidor local mapeado al contenedor en 0.0.0.0:5000"

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

security:
  - basicAuth: []

paths:
  "/":
    get:
      summary: "Página principal del sistema"
      description: >
        Retorna la plantilla **index.html**, que lista los chats filtrados,
        modelos disponibles, paginación, etc.

      operationId: getIndex
      security:
        - basicAuth: []

      parameters:
        - name: start_date
          in: query
          schema:
            type: string
            format: date
            default: "2024-10-10"  # Valor por defecto
            example: "2024-10-10"  # Ejemplo
          description: Fecha de inicio (yyyy-mm-dd)
        - name: end_date
          in: query
          schema:
            type: string
            format: date
            default: "2024-10-12"
            example: "2024-10-12"
          description: Fecha de fin (yyyy-mm-dd)
        - name: start_time
          in: query
          schema:
            type: string
            format: time
            default: "12:24"
            example: "12:24"
          description: Hora de inicio (HH:MM)
        - name: end_time
          in: query
          schema:
            type: string
            format: time
            default: "12:24"
            example: "12:24"
          description: Hora de fin (HH:MM)
        - name: model_name
          in: query
          schema:
            type: string
            default: "llama3:latest"
            example: "llama3:latest"
          description: Nombre del modelo a filtrar
        - name: rating_filter
          in: query
          schema:
            type: string
            enum: [positive, negative, none]
            default: "none"
            example: "none"
          description: Filtra chats con rating 'positive', 'negative' o 'none'
        - name: comment_filter
          in: query
          schema:
            type: string
            enum: [with, without]
            default: "without"
            example: "without"
          description: Filtra chats con/sin comentario
        - name: page
          in: query
          schema:
            type: integer
            default: 1
            example: 1
          description: Número de página para la paginación
        - name: per_page
          in: query
          schema:
            type: integer
            enum: [5, 10, 25]
            default: 5
            example: 5
          description: Tamaño de página (5, 10 o 25)

      responses:
        "200":
          description: "Página HTML principal con la lista de chats"
          content:
            text/html:
              schema:
                type: string
                example: "<!DOCTYPE html><html> ...</html>"
        "400":
          description: "Error de parámetros (fechas/horas mal formateadas)"
        "401":
          description: "No se proveyó o fue incorrecta la autenticación Basic"
        "500":
          description: "Error interno en el servidor"
